#!/usr/bin/python3

from sys import argv

def factorize(num):
    count = 2
    while ( ((num % count) != 0 ) and count <= num ):
        count += 1
    print("{}={}*{}".format(num, num//count, count))

def main():
    file = argv[1]
    with open(file, "r") as f:
        factorize(int(f.readline()))

if __name__ == '__main__':
    main()
